#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLANGXX="${CLANGXX:-clang++}"
SRC="$ROOT/src/slot-v2/cpp"

"$CLANGXX" --target=wasm32-unknown-unknown -std=c++20 -O3 \
  -nostdlib -ffreestanding -fno-exceptions -fno-rtti \
  -Wl,--no-entry -Wl,--export-memory \
  -Wl,--export=slot_v2_reset \
  -Wl,--export=slot_v2_lever \
  -Wl,--export=slot_v2_last_special \
  -Wl,--export=slot_v2_revival_finalize \
  -Wl,--export=slot_v2_entry_gate \
  -Wl,--export=slot_v2_revival_game \
  -Wl,--export=slot_v2_revival_state \
  -Wl,--export=slot_v2_bonus_cycle \
  -Wl,--export=slot_v2_bonus_transition \
  -Wl,--export=slot_v2_bonus_state \
  -Wl,--export=slot_v2_upper_comeback \
  -Wl,--export=slot_v2_at_single_transition \
  -Wl,--export=slot_v2_normal_at_trigger \
  -Wl,--export=slot_v2_section_reward \
  -Wl,--export=slot_v2_at_window \
  -Wl,--export=slot_v2_section_transition \
  -Wl,--export=slot_v2_special_zone \
  -Wl,--export=slot_v2_special_zone_result \
  -Wl,--export=slot_v2_cz_cycle \
  -Wl,--export=slot_v2_cz_finalize \
  -Wl,--export=slot_v2_normal_display_games \
  -Wl,--export=slot_v2_normal_actual_games \
  -Wl,--export=slot_v2_ceiling_at \
  -Wl,--export=slot_v2_ceiling_count \
  -Wl,--export=slot_v2_normal_progress \
  -Wl,--export=slot_v2_pending_events \
  -Wl,--export=slot_v2_at_cycle \
  -Wl,--export=slot_v2_normal_mode \
  -Wl,--export=slot_v2_normal_route \
  -Wl,--export=slot_v2_normal_ceiling_transition \
  -Wl,--export=slot_v2_at_resolution \
  -Wl,--export=slot_v2_bell_navigation_correct \
  -Wl,--export=slot_v2_bell_navigation_next \
  -Wl,--export=slot_v2_bell_navigation \
  -Wl,--export=slot_v2_point_count \
  -Wl,--export=slot_v2_stock_count \
  -Wl,--export=slot_v2_section_count \
  -Wl,--export=slot_v2_section_minimum \
  -Wl,--export=slot_v2_section_diff \
  -Wl,--export=slot_v2_machine_area \
  -Wl,--export=slot_v2_special_committed \
  -Wl,--export=slot_v2_at_games_left \
  -Wl,--export=slot_v2_at_tier \
  -Wl,--export=slot_v2_at_active \
  -Wl,--export=slot_v2_last_role \
  -Wl,--export=slot_v2_freeze_active \
  -Wl,--export=slot_v2_stop \
  -Wl,--export=slot_v2_stopped_position \
  -Wl,--export=slot_v2_stop_sequence \
  -Wl,--export=slot_v2_acquisition \
  -Wl,--export=slot_v2_validate_left \
  -Wl,--export=slot_v2_preflight \
  -Wl,--export=slot_v2_reel_ready_mask \
  -Wl,--export=slot_v2_validate_reel \
  -Wl,--export=slot_v2_assist_failure_mask \
  -Wl,--export=slot_v2_complete_special \
  -Wl,--export=slot_v2_special_result \
  -Wl,--export=slot_v2_phase \
  -Wl,--export=slot_v2_visible_symbol \
  -Wl,--export=slot_v2_symbol_at \
  -Wl,--initial-memory=131072 -Wl,--max-memory=16777216 \
  -o "$ROOT/web/slot-v2.wasm" \
  "$SRC/shared/memory.cpp" \
  "$SRC/shared/rng.cpp" \
  "$SRC/special/special_lottery.cpp" \
  "$SRC/special/special_result.cpp" \
  "$SRC/special/special_apply.cpp" \
  "$SRC/core/main_lottery.cpp" \
  "$SRC/core/lever.cpp" \
  "$SRC/reel/reel_strip.cpp" \
  "$SRC/reel/reel_validator.cpp" \
  "$SRC/core/preflight.cpp" \
  "$SRC/reel/reel_read.cpp" \
  "$SRC/reel/stop/stop_candidate.cpp" \
  "$SRC/reel/stop/rules/common_rule.cpp" \
  "$SRC/reel/stop/rules/bell_rule.cpp" \
  "$SRC/reel/stop/rules/replay_rule.cpp" \
  "$SRC/reel/stop/rules/cherry_rule.cpp" \
  "$SRC/reel/stop/rules/watermelon_rule.cpp" \
  "$SRC/reel/stop/rules/fallback_rule.cpp" \
  "$SRC/reel/stop/rules/rule_router.cpp" \
  "$SRC/reel/stop/rules/penguin_rule.cpp" \
  "$SRC/reel/stop/rules/strong_chance_rule.cpp" \
  "$SRC/reel/stop/rules/weak_chance_rule.cpp" \
  "$SRC/reel/stop/rules/one_medal_rule.cpp" \
  "$SRC/reel/stop/rules/miss_rule.cpp" \
  "$SRC/reel/stop/rules/entry_rule.cpp" \
  "$SRC/reel/stop/role_policy.cpp" \
  "$SRC/reel/stop/navigation.cpp" \
  "$SRC/reel/stop/bell_navigation.cpp" \
  "$SRC/reel/stop/assist_integrity.cpp" \
  "$SRC/reel/stop/assist_target.cpp" \
  "$SRC/reel/stop/stop_first.cpp" \
  "$SRC/reel/stop/stop_second.cpp" \
  "$SRC/reel/stop/stop_third.cpp" \
  "$SRC/reel/stop/stop_controller.cpp" \
  "$SRC/special/freeze_control.cpp" \
  "$SRC/reel/reel_acquisition.cpp" \
  "$SRC/normal/normal_progress.cpp" \
  "$SRC/normal/normal_at_trigger.cpp" \
  "$SRC/normal/normal_hit_entry.cpp" \
  "$SRC/entry/entry_gate.cpp" \
  "$SRC/entry/entry_gate_transition.cpp" \
  "$SRC/cz/cz_cycle.cpp" \
  "$SRC/cz/cz_finalize.cpp" \
  "$SRC/cz/cz_reward.cpp" \
  "$SRC/normal/normal_state.cpp" \
  "$SRC/normal/normal_progress_view.cpp" \
  "$SRC/normal/ceiling_catalog.cpp" \
  "$SRC/core/game_finalize.cpp" \
  "$SRC/core/pending_event.cpp" \
  "$SRC/core/runtime.cpp" \
  "$SRC/core/point_ledger.cpp" \
  "$SRC/core/accounting.cpp" \
  "$SRC/core/machine_state.cpp" \
  "$SRC/cz/cz_state.cpp" \
  "$SRC/bonus/bonus_state.cpp" \
  "$SRC/bonus/bonus_cycle.cpp" \
  "$SRC/bonus/bonus_transition.cpp" \
  "$SRC/bonus/bonus_entry_policy.cpp" \
  "$SRC/at/at_state.cpp" \
  "$SRC/at/at_cold.cpp" \
  "$SRC/at/at_lottery.cpp" \
  "$SRC/core/progress_event.cpp" \
  "$SRC/at/at_cycle.cpp" \
  "$SRC/cz/cz_lottery.cpp" \
  "$SRC/special/special_ceiling.cpp" \
  "$SRC/normal/normal_mode.cpp" \
  "$SRC/normal/normal_route.cpp" \
  "$SRC/normal/normal_ceiling.cpp" \
  "$SRC/normal/normal_ceiling_transition.cpp" \
  "$SRC/normal/normal_cycle_reset.cpp" \
  "$SRC/normal/normal_role_trigger.cpp" \
  "$SRC/core/setting_profile.cpp" \
  "$SRC/normal/normal_shortening.cpp" \
  "$SRC/normal/normal_high.cpp" \
  "$SRC/normal/normal_raw_lottery.cpp" \
  "$SRC/normal/normal_flow.cpp" \
  "$SRC/normal/normal_flow_transition.cpp" \
  "$SRC/at/at_resolution.cpp" \
  "$SRC/at/at_single_transition.cpp" \
  "$SRC/section/section_flow.cpp" \
  "$SRC/at/at_window.cpp" \
  "$SRC/at/at_table_transition.cpp" \
  "$SRC/at/at_stock_restart.cpp" \
  "$SRC/section/section_transition.cpp" \
  "$SRC/at/at_pending.cpp" \
  "$SRC/at/at_add_games.cpp" \
  "$SRC/at/at_internal_transition.cpp" \
  "$SRC/at/at_window_transition.cpp" \
  "$SRC/at/at_event.cpp" \
  "$SRC/special/special_zone.cpp" \
  "$SRC/special/special_zone_pending.cpp" \
  "$SRC/special/special_zone_transition.cpp" \
  "$SRC/special/upper_special.cpp" \
  "$SRC/special/upper_special_transition.cpp" \
  "$SRC/at/upper_comeback_state.cpp" \
  "$SRC/at/upper_comeback_cycle.cpp" \
  "$SRC/at/upper_comeback_transition.cpp" \
  "$SRC/revival/revival_cycle.cpp" \
  "$SRC/revival/revival_lottery.cpp" \
  "$SRC/revival/revival_state.cpp" \
  "$SRC/bonus/bonus_upgrade.cpp" \
  "$SRC/stock/stock_lottery.cpp" \
  "$SRC/stock/stock_count_lottery.cpp" \
  "$SRC/stock/stock_state.cpp" \
  "$SRC/section/section_state.cpp" \
  "$SRC/section/section_reward.cpp" \
  "$SRC/reel/reel_line.cpp" \
  "$SRC/core/session.cpp" \
  "$SRC/interface/wasm_exports.cpp"

echo "Built web/slot-v2.wasm from structured slot-v2/cpp sources."
