#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="$ROOT/.build-slot-v2"

rm -rf "$BUILD"
cmake -S "$ROOT" -B "$BUILD"
cmake --build "$BUILD" --target slot_v2_stop_test slot_v2_special_test slot_v2_navigation_test slot_v2_assist_test slot_v2_bell_navigation_test slot_v2_progress_test slot_v2_state_modules_test slot_v2_reel_candidate_test slot_v2_machine_state_test slot_v2_at_lottery_test slot_v2_at_cold_test slot_v2_feature_lottery_test slot_v2_special_apply_test slot_v2_stock_count_lottery_test slot_v2_preflight_test slot_v2_game_finalize_test slot_v2_at_cycle_test slot_v2_at_transition_test slot_v2_at_stock_restart_test slot_v2_progress_event_test slot_v2_flow_modules_test slot_v2_runtime_progress_test slot_v2_catalog_test slot_v2_normal_route_test slot_v2_normal_ceiling_transition_test slot_v2_normal_cycle_reset_test slot_v2_normal_role_trigger_test slot_v2_normal_flow_test slot_v2_runtime_normal_route_test slot_v2_normal_cz_cycle_test slot_v2_cz_finalize_test slot_v2_cz_reward_test slot_v2_section_reward_test slot_v2_flow_pending_test slot_v2_runtime_accounting_test slot_v2_section_transition_test slot_v2_runtime_gate_test slot_v2_bonus_cycle_test slot_v2_bonus_transition_test slot_v2_runtime_bonus_test slot_v2_upper_comeback_cycle_test slot_v2_at_single_transition_test slot_v2_at_omen_test slot_v2_normal_at_trigger_test slot_v2_runtime_normal_scope_test slot_v2_bonus_entry_policy_test slot_v2_special_zone_pending_test slot_v2_special_zone_transition_test slot_v2_runtime_special_zone_test slot_v2_upper_special_test slot_v2_runtime_revival_test slot_v2_revival_test slot_v2_runtime_normal_hit_test slot_v2_normal_hit_entry_test slot_v2_entry_gate_test slot_v2_runtime_entry_gate_test
"$BUILD/slot_v2_stop_test"
"$BUILD/slot_v2_special_test"
"$BUILD/slot_v2_navigation_test"
"$BUILD/slot_v2_assist_test"
"$BUILD/slot_v2_bell_navigation_test"
"$BUILD/slot_v2_progress_test"
"$BUILD/slot_v2_state_modules_test"
"$BUILD/slot_v2_reel_candidate_test"
"$BUILD/slot_v2_machine_state_test"
"$BUILD/slot_v2_at_lottery_test"
"$BUILD/slot_v2_at_cold_test"
"$BUILD/slot_v2_feature_lottery_test"
"$BUILD/slot_v2_special_apply_test"
"$BUILD/slot_v2_stock_count_lottery_test"
"$BUILD/slot_v2_preflight_test"
"$BUILD/slot_v2_game_finalize_test"
"$BUILD/slot_v2_at_cycle_test"
"$BUILD/slot_v2_at_transition_test"
"$BUILD/slot_v2_at_stock_restart_test"
"$BUILD/slot_v2_progress_event_test"
"$BUILD/slot_v2_flow_modules_test"
"$BUILD/slot_v2_runtime_progress_test"
"$BUILD/slot_v2_catalog_test"
"$BUILD/slot_v2_normal_route_test"
"$BUILD/slot_v2_normal_ceiling_transition_test"
"$BUILD/slot_v2_normal_cycle_reset_test"
"$BUILD/slot_v2_normal_role_trigger_test"
"$BUILD/slot_v2_normal_flow_test"
"$BUILD/slot_v2_runtime_normal_route_test"
"$BUILD/slot_v2_normal_cz_cycle_test"
"$BUILD/slot_v2_cz_finalize_test"
"$BUILD/slot_v2_cz_reward_test"
"$BUILD/slot_v2_section_reward_test"
"$BUILD/slot_v2_flow_pending_test"
"$BUILD/slot_v2_runtime_accounting_test"
"$BUILD/slot_v2_section_transition_test"
"$BUILD/slot_v2_runtime_gate_test"
"$BUILD/slot_v2_bonus_cycle_test"
"$BUILD/slot_v2_bonus_transition_test"
"$BUILD/slot_v2_runtime_bonus_test"
"$BUILD/slot_v2_upper_comeback_cycle_test"
"$BUILD/slot_v2_at_single_transition_test"
"$BUILD/slot_v2_at_omen_test"
"$BUILD/slot_v2_normal_at_trigger_test"
"$BUILD/slot_v2_runtime_normal_scope_test"
"$BUILD/slot_v2_bonus_entry_policy_test"
"$BUILD/slot_v2_special_zone_pending_test"
"$BUILD/slot_v2_special_zone_transition_test"
"$BUILD/slot_v2_runtime_special_zone_test"
"$BUILD/slot_v2_upper_special_test"
"$BUILD/slot_v2_runtime_revival_test"
"$BUILD/slot_v2_revival_test"
"$BUILD/slot_v2_runtime_normal_hit_test"
"$BUILD/slot_v2_normal_hit_entry_test"
"$BUILD/slot_v2_entry_gate_test"
"$BUILD/slot_v2_runtime_entry_gate_test"

echo "slot v2 native tests passed."
